@hostname = localhost
@port = 7261
@host = {{hostname}}:{{port}}
@contentType = application/json

## Get all running games

GET https://{{host}}/games/

### Create a new game

@gameid = d138bbe4-0f66-496e-a251-25b448ac043c

POST https://{{host}}/games
Content-Type: {{contentType}}

{
  "gameType": "Game6x4",
  "playerName": "Testplayer"
}

### Get a specific game

GET https://{{host}}/games/{{gameid}}

### Get all running games

GET https://{{host}}/games

### Set a move

POST https://{{host}}/games/{{gameid}}/moves
Content-Type: {{contentType}}

{
  "gameId": "{{gameid}}",
  "gameType": "Game6x4",
  "moveNumber": 1,
  "colorFields":  [
    { "color":"red" },
    { "color": "blue" },
    { "color": "green" },
    { "color": "yellow" }      
  ] 
}