// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppWithAppInsights.Data;

namespace WebAppWithAppInsights.Migrations
{
    [DbContext(typeof(BooksContext))]
    [Migration("20201229173224_InitBooks")]
    partial class InitBooks
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("WebAppWithAppInsights.Data.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Publisher")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BookId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Publisher = "Sample Pub",
                            Title = "book 1"
                        },
                        new
                        {
                            BookId = 2,
                            Publisher = "Sample Pub",
                            Title = "book 2"
                        },
                        new
                        {
                            BookId = 3,
                            Publisher = "Sample Pub",
                            Title = "book 3"
                        },
                        new
                        {
                            BookId = 4,
                            Publisher = "Sample Pub",
                            Title = "book 4"
                        },
                        new
                        {
                            BookId = 5,
                            Publisher = "Sample Pub",
                            Title = "book 5"
                        },
                        new
                        {
                            BookId = 6,
                            Publisher = "Sample Pub",
                            Title = "book 6"
                        },
                        new
                        {
                            BookId = 7,
                            Publisher = "Sample Pub",
                            Title = "book 7"
                        },
                        new
                        {
                            BookId = 8,
                            Publisher = "Sample Pub",
                            Title = "book 8"
                        },
                        new
                        {
                            BookId = 9,
                            Publisher = "Sample Pub",
                            Title = "book 9"
                        },
                        new
                        {
                            BookId = 10,
                            Publisher = "Sample Pub",
                            Title = "book 10"
                        },
                        new
                        {
                            BookId = 11,
                            Publisher = "Sample Pub",
                            Title = "book 11"
                        },
                        new
                        {
                            BookId = 12,
                            Publisher = "Sample Pub",
                            Title = "book 12"
                        },
                        new
                        {
                            BookId = 13,
                            Publisher = "Sample Pub",
                            Title = "book 13"
                        },
                        new
                        {
                            BookId = 14,
                            Publisher = "Sample Pub",
                            Title = "book 14"
                        },
                        new
                        {
                            BookId = 15,
                            Publisher = "Sample Pub",
                            Title = "book 15"
                        },
                        new
                        {
                            BookId = 16,
                            Publisher = "Sample Pub",
                            Title = "book 16"
                        },
                        new
                        {
                            BookId = 17,
                            Publisher = "Sample Pub",
                            Title = "book 17"
                        },
                        new
                        {
                            BookId = 18,
                            Publisher = "Sample Pub",
                            Title = "book 18"
                        },
                        new
                        {
                            BookId = 19,
                            Publisher = "Sample Pub",
                            Title = "book 19"
                        },
                        new
                        {
                            BookId = 20,
                            Publisher = "Sample Pub",
                            Title = "book 20"
                        },
                        new
                        {
                            BookId = 21,
                            Publisher = "Sample Pub",
                            Title = "book 21"
                        },
                        new
                        {
                            BookId = 22,
                            Publisher = "Sample Pub",
                            Title = "book 22"
                        },
                        new
                        {
                            BookId = 23,
                            Publisher = "Sample Pub",
                            Title = "book 23"
                        },
                        new
                        {
                            BookId = 24,
                            Publisher = "Sample Pub",
                            Title = "book 24"
                        },
                        new
                        {
                            BookId = 25,
                            Publisher = "Sample Pub",
                            Title = "book 25"
                        },
                        new
                        {
                            BookId = 26,
                            Publisher = "Sample Pub",
                            Title = "book 26"
                        },
                        new
                        {
                            BookId = 27,
                            Publisher = "Sample Pub",
                            Title = "book 27"
                        },
                        new
                        {
                            BookId = 28,
                            Publisher = "Sample Pub",
                            Title = "book 28"
                        },
                        new
                        {
                            BookId = 29,
                            Publisher = "Sample Pub",
                            Title = "book 29"
                        },
                        new
                        {
                            BookId = 30,
                            Publisher = "Sample Pub",
                            Title = "book 30"
                        },
                        new
                        {
                            BookId = 31,
                            Publisher = "Sample Pub",
                            Title = "book 31"
                        },
                        new
                        {
                            BookId = 32,
                            Publisher = "Sample Pub",
                            Title = "book 32"
                        },
                        new
                        {
                            BookId = 33,
                            Publisher = "Sample Pub",
                            Title = "book 33"
                        },
                        new
                        {
                            BookId = 34,
                            Publisher = "Sample Pub",
                            Title = "book 34"
                        },
                        new
                        {
                            BookId = 35,
                            Publisher = "Sample Pub",
                            Title = "book 35"
                        },
                        new
                        {
                            BookId = 36,
                            Publisher = "Sample Pub",
                            Title = "book 36"
                        },
                        new
                        {
                            BookId = 37,
                            Publisher = "Sample Pub",
                            Title = "book 37"
                        },
                        new
                        {
                            BookId = 38,
                            Publisher = "Sample Pub",
                            Title = "book 38"
                        },
                        new
                        {
                            BookId = 39,
                            Publisher = "Sample Pub",
                            Title = "book 39"
                        },
                        new
                        {
                            BookId = 40,
                            Publisher = "Sample Pub",
                            Title = "book 40"
                        },
                        new
                        {
                            BookId = 41,
                            Publisher = "Sample Pub",
                            Title = "book 41"
                        },
                        new
                        {
                            BookId = 42,
                            Publisher = "Sample Pub",
                            Title = "book 42"
                        },
                        new
                        {
                            BookId = 43,
                            Publisher = "Sample Pub",
                            Title = "book 43"
                        },
                        new
                        {
                            BookId = 44,
                            Publisher = "Sample Pub",
                            Title = "book 44"
                        },
                        new
                        {
                            BookId = 45,
                            Publisher = "Sample Pub",
                            Title = "book 45"
                        },
                        new
                        {
                            BookId = 46,
                            Publisher = "Sample Pub",
                            Title = "book 46"
                        },
                        new
                        {
                            BookId = 47,
                            Publisher = "Sample Pub",
                            Title = "book 47"
                        },
                        new
                        {
                            BookId = 48,
                            Publisher = "Sample Pub",
                            Title = "book 48"
                        },
                        new
                        {
                            BookId = 49,
                            Publisher = "Sample Pub",
                            Title = "book 49"
                        },
                        new
                        {
                            BookId = 50,
                            Publisher = "Sample Pub",
                            Title = "book 50"
                        },
                        new
                        {
                            BookId = 51,
                            Publisher = "Sample Pub",
                            Title = "book 51"
                        },
                        new
                        {
                            BookId = 52,
                            Publisher = "Sample Pub",
                            Title = "book 52"
                        },
                        new
                        {
                            BookId = 53,
                            Publisher = "Sample Pub",
                            Title = "book 53"
                        },
                        new
                        {
                            BookId = 54,
                            Publisher = "Sample Pub",
                            Title = "book 54"
                        },
                        new
                        {
                            BookId = 55,
                            Publisher = "Sample Pub",
                            Title = "book 55"
                        },
                        new
                        {
                            BookId = 56,
                            Publisher = "Sample Pub",
                            Title = "book 56"
                        },
                        new
                        {
                            BookId = 57,
                            Publisher = "Sample Pub",
                            Title = "book 57"
                        },
                        new
                        {
                            BookId = 58,
                            Publisher = "Sample Pub",
                            Title = "book 58"
                        },
                        new
                        {
                            BookId = 59,
                            Publisher = "Sample Pub",
                            Title = "book 59"
                        },
                        new
                        {
                            BookId = 60,
                            Publisher = "Sample Pub",
                            Title = "book 60"
                        },
                        new
                        {
                            BookId = 61,
                            Publisher = "Sample Pub",
                            Title = "book 61"
                        },
                        new
                        {
                            BookId = 62,
                            Publisher = "Sample Pub",
                            Title = "book 62"
                        },
                        new
                        {
                            BookId = 63,
                            Publisher = "Sample Pub",
                            Title = "book 63"
                        },
                        new
                        {
                            BookId = 64,
                            Publisher = "Sample Pub",
                            Title = "book 64"
                        },
                        new
                        {
                            BookId = 65,
                            Publisher = "Sample Pub",
                            Title = "book 65"
                        },
                        new
                        {
                            BookId = 66,
                            Publisher = "Sample Pub",
                            Title = "book 66"
                        },
                        new
                        {
                            BookId = 67,
                            Publisher = "Sample Pub",
                            Title = "book 67"
                        },
                        new
                        {
                            BookId = 68,
                            Publisher = "Sample Pub",
                            Title = "book 68"
                        },
                        new
                        {
                            BookId = 69,
                            Publisher = "Sample Pub",
                            Title = "book 69"
                        },
                        new
                        {
                            BookId = 70,
                            Publisher = "Sample Pub",
                            Title = "book 70"
                        },
                        new
                        {
                            BookId = 71,
                            Publisher = "Sample Pub",
                            Title = "book 71"
                        },
                        new
                        {
                            BookId = 72,
                            Publisher = "Sample Pub",
                            Title = "book 72"
                        },
                        new
                        {
                            BookId = 73,
                            Publisher = "Sample Pub",
                            Title = "book 73"
                        },
                        new
                        {
                            BookId = 74,
                            Publisher = "Sample Pub",
                            Title = "book 74"
                        },
                        new
                        {
                            BookId = 75,
                            Publisher = "Sample Pub",
                            Title = "book 75"
                        },
                        new
                        {
                            BookId = 76,
                            Publisher = "Sample Pub",
                            Title = "book 76"
                        },
                        new
                        {
                            BookId = 77,
                            Publisher = "Sample Pub",
                            Title = "book 77"
                        },
                        new
                        {
                            BookId = 78,
                            Publisher = "Sample Pub",
                            Title = "book 78"
                        },
                        new
                        {
                            BookId = 79,
                            Publisher = "Sample Pub",
                            Title = "book 79"
                        },
                        new
                        {
                            BookId = 80,
                            Publisher = "Sample Pub",
                            Title = "book 80"
                        },
                        new
                        {
                            BookId = 81,
                            Publisher = "Sample Pub",
                            Title = "book 81"
                        },
                        new
                        {
                            BookId = 82,
                            Publisher = "Sample Pub",
                            Title = "book 82"
                        },
                        new
                        {
                            BookId = 83,
                            Publisher = "Sample Pub",
                            Title = "book 83"
                        },
                        new
                        {
                            BookId = 84,
                            Publisher = "Sample Pub",
                            Title = "book 84"
                        },
                        new
                        {
                            BookId = 85,
                            Publisher = "Sample Pub",
                            Title = "book 85"
                        },
                        new
                        {
                            BookId = 86,
                            Publisher = "Sample Pub",
                            Title = "book 86"
                        },
                        new
                        {
                            BookId = 87,
                            Publisher = "Sample Pub",
                            Title = "book 87"
                        },
                        new
                        {
                            BookId = 88,
                            Publisher = "Sample Pub",
                            Title = "book 88"
                        },
                        new
                        {
                            BookId = 89,
                            Publisher = "Sample Pub",
                            Title = "book 89"
                        },
                        new
                        {
                            BookId = 90,
                            Publisher = "Sample Pub",
                            Title = "book 90"
                        },
                        new
                        {
                            BookId = 91,
                            Publisher = "Sample Pub",
                            Title = "book 91"
                        },
                        new
                        {
                            BookId = 92,
                            Publisher = "Sample Pub",
                            Title = "book 92"
                        },
                        new
                        {
                            BookId = 93,
                            Publisher = "Sample Pub",
                            Title = "book 93"
                        },
                        new
                        {
                            BookId = 94,
                            Publisher = "Sample Pub",
                            Title = "book 94"
                        },
                        new
                        {
                            BookId = 95,
                            Publisher = "Sample Pub",
                            Title = "book 95"
                        },
                        new
                        {
                            BookId = 96,
                            Publisher = "Sample Pub",
                            Title = "book 96"
                        },
                        new
                        {
                            BookId = 97,
                            Publisher = "Sample Pub",
                            Title = "book 97"
                        },
                        new
                        {
                            BookId = 98,
                            Publisher = "Sample Pub",
                            Title = "book 98"
                        },
                        new
                        {
                            BookId = 99,
                            Publisher = "Sample Pub",
                            Title = "book 99"
                        },
                        new
                        {
                            BookId = 100,
                            Publisher = "Sample Pub",
                            Title = "book 100"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
